#!/bin/bash
args=("$@")
DEV_CONTAINER="fillgaps_dev_gpu_0"


## define volumes to be mounted
ROOT=$(pwd)
BINPATH=$(pwd)/fillgaps
DATAPATH=$(pwd)/data
EXPPATH=$(pwd)/experiments
RESULTSPATH=$(pwd)/results




ROOTDESTPATH=/home/FillGaps
BINDESTPATH=/home/FillGaps/fillgaps
DATADESTPATH=/home/FillGaps/data
EXPDISTPATH=/home/FillGaps/experiments
RESULTSDISTPATH=/home/FillGaps/results

user="${USER}"


## build container
docker run -itd \
  --gpus '"device=0"'\
  -e NVIDIA_VISIBLE_DEVICES=all \
  -e DOCKER_USER="${user}" \
  -e USER="${user}" \
  --name "${DEV_CONTAINER}" \
  --hostname $HOSTNAME'_DOCKER_0'\
  -v ${DATAPATH}:${DATADESTPATH} \
  -v ${BINPATH}:${BINDESTPATH} \
  -v ${EXPPATH}:${EXPDISTPATH} \
  -v ${RESULTSPATH}:${RESULTSDISTPATH} \
  -it fillgaps:latest \
  /bin/bash
