#!/bin/bash

# Default value is 0 if no argument is provided
NUM=${1:-0}

DEV_CONTAINER="analytics_dev_gpu_${NUM}"
user="${USER}"
user="mrsinetuser"

# Check if the container exists
if [ "$(docker ps -aq -f name=^${DEV_CONTAINER}$)" ]; then
    echo "${DEV_CONTAINER} already exists ... recreating a new one"
    docker stop ${DEV_CONTAINER}
    docker rm ${DEV_CONTAINER}
fi

## define volumes to be mounted
ROOT=$(pwd)
DATAPATH=/media/flucchetti/DATA_8TB/MRSI/Mindfulteen/derivatives
echo "DEV_ANA path set to $ROOT"
echo "DATA path set to $DATAPATH"

FILLGAPSPATH=${ROOT}/fillgaps
TOOLPATH=${ROOT}/tools
EXPPATH=${ROOT}/experiments
RESULTSPATH=${ROOT}/results

## define mount destination
ROOTDESTPATH=/home/mrsinetuser
DATADESTPATH=/home/mrsinetuser/data
FILLGAPSDESTPATH=${ROOTDESTPATH}/fillgaps
TOOLDESTPATH=${ROOTDESTPATH}/tools
EXPDISTPATH=${ROOTDESTPATH}/experiments
RESULTSDISTPATH=${ROOTDESTPATH}/results


## build container
docker run -itd \
  --gpus "device=${NUM}" \
  -e NVIDIA_VISIBLE_DEVICES=all \
  -e DOCKER_USER="${user}" \
  -e USER="${user}" \
  --name "${DEV_CONTAINER}" \
  --hostname $HOSTNAME'_DOCKER_'${NUM} \
  -v ${DATAPATH}:${DATADESTPATH} \
  -v ${FILLGAPSPATH}:${FILLGAPSDESTPATH} \
  -v ${TOOLPATH}:${TOOLDESTPATH} \
  -v ${EXPPATH}:${EXPDISTPATH} \
  -v ${RESULTSPATH}:${RESULTSDISTPATH} \
  -it mrsinet:latest \
  /bin/bash

docker exec -it ${DEV_CONTAINER} pip3 install -e .
# Add input prompt here
read -p "Do you want to enter the Docker container? (Y/n) " answer
case ${answer:0:1} in
    y|Y )
        docker exec -it ${DEV_CONTAINER} bash
    ;;
    * )
        echo "Skipping entering the container."
    ;;
esac
